language: c

before_install: {}


script:
  - docker build -t "$DOCKER_USERNAME/$DOCKER_TAG" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME/$DOCKER_TAG"

git:
  submodules: true

services:
  - docker
